# Generated by Django 4.0.5 on 2022-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attendees_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview_at',
            field=models.DateTimeField(unique_for_date=True),
        ),
    ]
