# Generated by Django 4.0.5 on 2022-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_recipe_preview_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview_at',
            field=models.DateField(unique_for_date='preview_at'),
        ),
    ]
