# Generated by Django 4.0.5 on 2022-07-04 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('becoffe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('arrival_time', models.DateField(max_length=100)),
                ('departure_time', models.DateField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
