# Generated by Django 4.0.5 on 2022-07-05 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('becoffe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField()),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInPromo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('promo_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='account_type',
            new_name='Admin',
        ),
        migrations.AddField(
            model_name='promo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preview_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promo',
            name='admin_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author_id',
            field=models.IntegerField(),
        ),
    ]
