# Generated by Django 4.0.5 on 2022-07-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('becoffe_app', '0003_rename_name_recipe_title_alter_recipe_preview_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='departure_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becoffe_app.users'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becoffe_app.users'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becoffe_app.users'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersinpromo',
            name='promo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becoffe_app.promo'),
        ),
        migrations.AlterField(
            model_name='usersinpromo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='becoffe_app.users'),
        ),
    ]
